name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Make Action'
        required: true
        default: 'build'
        type: choice
        options:
          - build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: make ${{ inputs.action }}