name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Make Action'
        required: true
        default: 'build'
        type: choice
        options:
          - build

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make ${{ inputs.action }} 
